export const DASHBOARD_READ = 'DASHBOARD_READ'
export const DASHBOARD_EXPORT = 'DASHBOARD_EXPORT'
export const DATA_UPLOAD = 'DATA_UPLOAD'
export const HELP_TICKET_CREATE = 'HELP_TICKET_CREATE'
export const HELP_TICKET_READ = 'HELP_TICKET_READ'
export const ADMIN_USERS = 'ADMIN_USERS'
export const ADMIN_THRESHOLDS = 'ADMIN_THRESHOLDS'
export const ADMIN_DATASETS = 'ADMIN_DATASETS'
export const ADMIN_AUDIT = 'ADMIN_AUDIT'
export const PLANNING_EDIT = 'PLANNING_EDIT'
export const ROI_EDIT = 'ROI_EDIT'

const permissions = {
  DASHBOARD_READ,
  DASHBOARD_EXPORT,
  DATA_UPLOAD,
  HELP_TICKET_CREATE,
  HELP_TICKET_READ,
  ADMIN_USERS,
  ADMIN_THRESHOLDS,
  ADMIN_DATASETS,
  ADMIN_AUDIT,
  PLANNING_EDIT,
  ROI_EDIT
}

export default permissions
