"""COA (Course of Action) generation router.

Produces deterministic, explainable COA recommendations by aggregating
scoring outputs. No ML/LLM; rules are simple, traceable heuristics.
"""

from fastapi import APIRouter, Query
from typing import Optional, Dict, Any, List
from datetime import datetime
from . import scoring

router = APIRouter()


def _now_iso():
    return datetime.utcnow().isoformat() + 'Z'


@router.get('/command/coa/recommendations')
def recommendations(fy: Optional[int] = Query(None), qtr: Optional[int] = Query(None), rsid_prefix: Optional[str] = Query(None)) -> Dict[str, Any]:
    params = {'fy': fy, 'qtr': qtr, 'rsid_prefix': rsid_prefix}
    # call scoring endpoints (they are deterministic functions)
    try:
        mc = scoring.market_capacity(fy=fy, qtr=qtr, rsid_prefix=rsid_prefix)
    except Exception:
        mc = {'score': 0, 'tier': 'LOW', 'components': {}, 'missing_data': []}
    try:
        mf = scoring.mission_feasibility(fy=fy, qtr=qtr, rsid_prefix=rsid_prefix)
    except Exception:
        mf = {'score': 0, 'tier': 'LOW', 'components': {}, 'missing_data': []}
    try:
        ra = scoring.resource_alignment(fy=fy, qtr=qtr, rsid_prefix=rsid_prefix)
    except Exception:
        ra = {'score': 0, 'tier': 'LOW', 'components': {}, 'missing_data': []}

    coas: List[Dict[str, Any]] = []

    # Deterministic rule 1: If market capacity is HIGH but mission feasibility LOW -> increase targeting
    if mc.get('tier') == 'HIGH' and mf.get('tier') == 'LOW':
        coas.append({
            'id': 'COA1',
            'title': 'Increase Targeting in High-Potential Areas',
            'rationale': 'Market capacity is high while feasibility is low; shift targeting to high-potential segments.',
            'projected_impact_score': round((mc.get('score',0) + 20),2),
            'risk_tier': 'MODERATE',
            'resource_requirement_level': 'MEDIUM',
            'supporting_scores': {'market_capacity': mc.get('score'), 'mission_feasibility': mf.get('score')}
        })

    # Deterministic rule 2: If resource alignment is LOW -> reallocate spend to priority schools
    if ra.get('tier') == 'LOW':
        coas.append({
            'id': 'COA2',
            'title': 'Reallocate Spend Toward Priority Schools',
            'rationale': 'Resource alignment indicates misalignment; focus spend on high-return schools.',
            'projected_impact_score': round((100 - ra.get('score',0)) * 0.5,2),
            'risk_tier': 'MODERATE',
            'resource_requirement_level': 'HIGH',
            'supporting_scores': {'resource_alignment': ra.get('score')}
        })

    # Deterministic rule 3: Fallback conservative COA when no strong signals
    if not coas:
        coas.append({
            'id': 'COA0',
            'title': 'Conservative: Maintain Current Posture and Monitor',
            'rationale': 'No clear deterministic COA emerges from current scores; recommend monitoring and targeted checks.',
            'projected_impact_score': round((mc.get('score',0) + mf.get('score',0) + ra.get('score',0))/3.0,2),
            'risk_tier': 'LOW',
            'resource_requirement_level': 'LOW',
            'supporting_scores': {'market_capacity': mc.get('score'), 'mission_feasibility': mf.get('score'), 'resource_alignment': ra.get('score')}
        })

    problem_statement = 'Autogenerated problem statement: reconcile market potential, mission feasibility, and resource alignment to improve recruiting outcomes.'

    return {'status': 'ok', 'data_as_of': _now_iso(), 'problem_statement': problem_statement, 'coas': coas, 'missing_data': list(set((mc.get('missing_data',[]) or []) + (mf.get('missing_data',[]) or []) + (ra.get('missing_data',[]) or [])))}

